language: ruby
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
after_success:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX='.*' BRANCH_TO_MERGE_INTO=deploy GITHUB_REPO=ruupert/eduroam-location-api
  /tmp/travis-automerge
deploy:
  provider: heroku
  api_key:
    secure: Er2v9jKClqHfQA1D/iiz1M8p/InX9JlxzgO5aMYD7X7I/EHsMbHKo0Os0hzUAYHS2baAm379OXkzN2x3NS1A5GNgpzAi8E9vLvChh3+qT+mh1gjVJtPEZlpVv6hApQGt9ZEJsPyqm2B9C0IQeDDjfwcb7hWGYgSG/8ZU51TIZAdmkwV3dzR/QXBsipTEbW4KC2HM2acWAhZJt27cr12H5/lzI0FkuAi+R332lQCgjEwL/4n02VRzuQGIfDgEQ+Hv4jel/gUxho7qjshPiOffwaXIhpH82+PCzL3g16OGKP4yIgo4xk3aCL5JC6TfVXrP20+7IDNI9SKiIQ6jE7Yt+eyemPwgrtertoQavbQ4H38YdRwsLsQLcDnLqs0N2+AXqFoCBbs23FJamlGnIRWi7XLRxnpFLIWlwqehb4oSVvcUO/WCxo6GKg1sVsKPrg4FyDfeZe4YGtmgBcyii6yEwUU5V4TPWYu3t1dvyMWKqVVyUp6iEkWgs/MW8N3P821EH584xKaT8vLHzZSo0w1m7Cu/tCViPNtTWummGuqmXnUgwLiWdJfXBNqevgTpHeXxtWIjaUi3swO/Y8OD64LabLZCtcdIfo/4cYKgHAeJuETnSoPmcOEQxsjaBlJkcdjo3jAy2ks7oYGI+Xqsl9T/qizSU2hwzGmz9nhCOHavxYg=
  app: eduroam-api
  on:
    repo: ruupert/eduroam-location-api
env:
  global:
    secure: edXCFYXSefyoTMeeILxh9PJmZDPdurvon4JSDo13d6ki8hmALRRrt4iBQIp25dX5D1ngjkqkaSSY4TzlHD7X/5iQ/Q+5zHXzAcqAT4W0XlxKVDeng9O2gU7B9JcKkUYufgdUZl3ubOoR2nyKkXTzBQgxL1/IxR7/Pj0f//jm13/IpOtsnU6NRQZPNvcnotDo2S+QLNKEKDMbNWYJKzrvxN0nIVkpv+walRd017mNbwkylBTh8jNL7D6Ltlu7zlYp41mbkdVYs3W35fYwzbsUS6lKtCbcbOfsUFYripuvxV2bE1xaT/0RSoz1RZLLqN8JyvYZRqiLwqP0R4+LRkq3jiSWBEw0RatP7A1B0U+t2jiznr0LM6jQf7uENTNZ9GV0p5vLMxqNvN+j9XW5fy2McOWppFKGSUlKLitaafmcW+qqYz1DJP7jXr8cGed0Q0YMSnlsWRqHBR3bas13y6c9Tjo5EG/0SRhgy5eRoEmb1xdkOHeo8600/FZb/4vrrula4FbMMhyaomgv0xs+qRDN3WVqQROau/JWbLMerItH+M12JB4YDdZsP0SgTRhq9RnxA8DEsikAboziYD8dtJIRzJWyUUnxubvldWaHiCHd84Z+9eOPoKJ1a5UpRfErqj0bq8SDuu1HCr8AJbzwkSJ3YT/3CElNyWDYdXZsMbqX40k=
