language: ruby
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
branches:
except:
- deploy
- master
after_success:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX='^development' BRANCH_TO_MERGE_INTO=deploy GITHUB_REPO=ruupert/eduroam-location-api
  /tmp/travis-automerge
env:
  global:
    secure: edXCFYXSefyoTMeeILxh9PJmZDPdurvon4JSDo13d6ki8hmALRRrt4iBQIp25dX5D1ngjkqkaSSY4TzlHD7X/5iQ/Q+5zHXzAcqAT4W0XlxKVDeng9O2gU7B9JcKkUYufgdUZl3ubOoR2nyKkXTzBQgxL1/IxR7/Pj0f//jm13/IpOtsnU6NRQZPNvcnotDo2S+QLNKEKDMbNWYJKzrvxN0nIVkpv+walRd017mNbwkylBTh8jNL7D6Ltlu7zlYp41mbkdVYs3W35fYwzbsUS6lKtCbcbOfsUFYripuvxV2bE1xaT/0RSoz1RZLLqN8JyvYZRqiLwqP0R4+LRkq3jiSWBEw0RatP7A1B0U+t2jiznr0LM6jQf7uENTNZ9GV0p5vLMxqNvN+j9XW5fy2McOWppFKGSUlKLitaafmcW+qqYz1DJP7jXr8cGed0Q0YMSnlsWRqHBR3bas13y6c9Tjo5EG/0SRhgy5eRoEmb1xdkOHeo8600/FZb/4vrrula4FbMMhyaomgv0xs+qRDN3WVqQROau/JWbLMerItH+M12JB4YDdZsP0SgTRhq9RnxA8DEsikAboziYD8dtJIRzJWyUUnxubvldWaHiCHd84Z+9eOPoKJ1a5UpRfErqj0bq8SDuu1HCr8AJbzwkSJ3YT/3CElNyWDYdXZsMbqX40k=
deploy:
  provider: heroku
  api_key:
    secure: oS6tiuMvl2oQ3/J1v6LTxMWBz0coLCRjeWgSV7JZ+LLyTpEQhGG9GwqZLZFq4pYdm/7sXzSSqNxE5GaEk5VPlVFb6h5b05Cl1txYkrqEeNM9EgP/fTe5sxLy4JbwbEzOU2Qi5M7/YUluK1jqJAOMGcv68IReMKygnUnDUQfxZAlLiLx8Ij17757TvmaojSPK4mAIG3rAGinSd5wwZBSAvbQ38vB3EXUjOrRHcAY+XTECTePkHH/YaKfh3eye0CJY0ckYAmk3U20g1gXxrvQiXKhbzvxsnLCtIVaVqh7Y7e05oSznf5ZYUlLkGh8YdUeRLyJ4rIk0dUH1fzs6fesrOmWX21Q+wG2Y+37JChF3D8yzTuYE69ItmkqZVpIBpZDgqNSQB1MXfG3+zzK1pz6IH/PaoyGTjyyWZE1Jqb7nQ/QOzK5K5UmAoN/QME9keJYfIefM8he8SgoUCT0K/kUWAivMz5+Xo/UQ7ZTDGzXdMx3pWGPLXyBlNm9RdPHYJ061K7nQgLERihlCEYZkSiWVy6IiScUuhnCYERU8zacrgXZrzGXGTc0S5QBaukSWjmC3V76lPnE1Qb7vFc0xguM5FPfR7EY/nYxxdhxmKoqZO6/DrA8hF9eDMcagZ/KZRH9M13R7hD0YEZpwrJPx390Sklx/75Qjtbc+ab5KZ1DCm18=
  app: eduroam-api
  on:
    repo: ruupert/eduroam-location-api
    branch: deploy
